# Header

menu:
  主页: /
  分类: /categories
  随笔: /tags/

# SubNav
subnav:
  github: "https://github.com/fuzhengwei"
  #weibo: "#"
  #rss: "#"
  #zhihu: "#"
  #qq: "#"
  #weixin: "13521408777"
  jianshu: "https://www.jianshu.com/u/6277de401399"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:184172133@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link: 'more'
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '感谢给我默默加油的你！'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /img/pay_zhifubao.png
# 微信二维码图片地址
weixin: /img/pay_weixin.png

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '尚不存在'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /img/touxiang.png

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
#gitment_owner: false      #你的 GitHub ID
#gitment_repo: 'fuzhengwei.github.io'          #存储评论的 repo
#gitment_oauth:
#  client_id: 'cc86f59495cf11ebf26b'           #client ID
#  client_secret: '540fce73bdc2e4733c3cf6eb041fa7bd0057e312'       #client secret

# 配置gitalk
gitalk:
  enable: true
  client_id: cc86f59495cf11ebf26b
  client_secret: e2dc4ec1d87b3744e29412623fa94e70ae099636
  repo: fuzhengwei.github.com
  owner: fuzhengwei
  admin: fuzhengwei

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends:
  个人博客: http://www.itstack.org

aboutme: 付政委 13年毕业于白城师范软件工程专业，Java出身码农一只，由于工作需要逐渐学习了C#、PHP。其中最热爱Java编程，对线程并发、JVM与Web有浓厚兴趣；从2012年培训实习到2015年8月24日就职与北京中软国际烟草行业本部，2015年8月25日开始就职于京东金融技术与数据服务部；本人热爱生活，热爱电子设备，喜欢和父母一起生活。
